# This is a workflow to translate a Hugo site using a Go-based translator.

name: translator

# Controls when the action will run.
on:
  push:
    branches:
      - '**'         # matches every branch
      - '!master'   # excludes master
      - '!main'     # excludes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web Repo
        uses: actions/checkout@v2
        with:
          repository: davidgs/pi-hands-on
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: ./pi-hands-on
      - name: Checkout Translate
        uses: actions/checkout@v2
        with:
          repository: davidgs/Translator
          path: ./translate
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.133.0'
          extended: true
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.23'
      - name: Build Translator
        run: cd ./translate; go build translate.go
      - name: Create Secret
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "./translate/google-secret.json"
          json: ${{ secrets.TRANSLATE_SECRET }}
      - name: Translate
        run: cd ./translate; ./translate ../pi-hands-on/content/
      - name: ReCommit
        # run: cd ./DavidgsWeb
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Apply Auto-Translations
          # branch: main
          # file_pattern: index.*.md
          repository: ./pi-hands-on
